/**
 * Pagila stores `country.country` as a free-text name. The Stores table
 * needs a 2-letter flag-style badge, so we map the long-tail Pagila
 * country names to their ISO-3166-1 alpha-2 codes here.
 *
 * Anything outside the map falls back to the uppercased first two
 * letters of the country name so the cell stays consistent rather than
 * blank.
 */

const ISO_CODES: Record<string, string> = {
  Afghanistan: "AF",
  "American Samoa": "AS",
  Algeria: "DZ",
  Angola: "AO",
  Anguilla: "AI",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahrain: "BH",
  Bangladesh: "BD",
  Belarus: "BY",
  Bolivia: "BO",
  Brazil: "BR",
  Brunei: "BN",
  Bulgaria: "BG",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Congo: "CG",
  "Czech Republic": "CZ",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  Estonia: "EE",
  Ethiopia: "ET",
  "Faroe Islands": "FO",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  Gambia: "GM",
  Germany: "DE",
  Greece: "GR",
  Greenland: "GL",
  "Holy See (Vatican City State)": "VA",
  "Hong Kong": "HK",
  Hungary: "HU",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Israel: "IL",
  Italy: "IT",
  "Ivory Coast": "CI",
  Japan: "JP",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kuwait: "KW",
  Latvia: "LV",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Mexico: "MX",
  Moldova: "MD",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  "North Korea": "KP",
  Oman: "OM",
  Pakistan: "PK",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  "Puerto Rico": "PR",
  Romania: "RO",
  "Runion": "RE",
  "Russian Federation": "RU",
  "Saint Vincent and the Grenadines": "VC",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Slovakia: "SK",
  "South Africa": "ZA",
  "South Korea": "KR",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Sweden: "SE",
  Switzerland: "CH",
  Taiwan: "TW",
  Tanzania: "TZ",
  Thailand: "TH",
  Tonga: "TO",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  Tuvalu: "TV",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  Venezuela: "VE",
  Vietnam: "VN",
  "Virgin Islands, U.S.": "VI",
  Yemen: "YE",
  Yugoslavia: "YU",
  Zambia: "ZM",
};

export function countryCodeFor(country: string | null | undefined): string {
  const trimmed = country?.trim();
  if (!trimmed) return "??";
  return ISO_CODES[trimmed] ?? trimmed.slice(0, 2).toUpperCase();
}
