coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

flag_management:
  individual_flags:
    - name: unit
      carryforward: true
    - name: integration
      carryforward: true

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: false
